export enum Route {
  Home = "/",
  About = "/about",
  Categories = "/category",
  Category = "/category/[category]",
  SubCategory = "/category/[category]/[subCategory]",
  Item = "/category/[category]/[subCategory]/[item]",
  // Gallery = "/gallery",
  // Portrait = "/gallery/portrait",
  // Concert = "/gallery/concert",
  // Fauna = "/gallery/fauna",
  // Flora = "/gallery/Flora",
  // Travel = "/gallery/travel",
  // Artwork = "/artwork",
  // Cartoon = "/artwork/cartoon",
  // Lineart = "/artwork/lineart",
  // Painting = "/artwork/painting",
  Pricing = "/pricing",
  Otherprojects = "/otherprojects",
  Contact = "/contact",
}
